
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/ApiTest
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml

logging:
  level:
    org:
      springframework:
        jdbc:
          core: DEBUG
